# NumPy

NumPy stands for **Numerical Python**

NumPy has a many application in field of ML, DL, Computer vision etc..Tensorflow also used NumPy for its designing.NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [1]:
import numpy as np

In [2]:
import array

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

This is a n-dimensional array.

In [4]:
np.array([1,2,3,4,5,"skm",4+8j])

array(['1', '2', '3', '4', '5', 'skm', '(4+8j)'], dtype='<U11')

In [5]:
np.array([1,2,3,4.5,6.0])
#here it is to be noted that th entire array is ocnverted in to floating point
#up-casting the data automatically

array([1. , 2. , 3. , 4.5, 6. ])

In [6]:
np.array([[1,3],[3,4],[6,7]])


#this is a example of 2-D array

array([[1, 3],
       [3, 4],
       [6, 7]])

In [7]:
np.array([[1,3],[3,4],[6,7,8]])
#here dimension of array is not same. It will give list of array

<ipython-input-7-8535d3632fd0>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [8]:
np.array([[[1,3],[3,4]],[[3,4],[6,7]]])

#this is a example of 3-D array

array([[[1, 3],
        [3, 4]],

       [[3, 4],
        [6, 7]]])

In [9]:
np.array([1,2,3],ndmin=3)

#will add dimension to the data

array([[[1, 2, 3]]])

In [10]:
np.array([1,2,3],dtype=complex)


array([1.+0.j, 2.+0.j, 3.+0.j])

In [11]:
np.array([(1,2),(4,5)])

array([[1, 2],
       [4, 5]])

In [13]:
arr=np.array([(1,2),(4,5)], dtype=[("a",'<i2'),("b",'<i8')])

In [14]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [15]:
type(arr[0][0])

numpy.int16

In [16]:
type(arr[0][1])

numpy.int64

It is to be noted that i2 represents 16 bit, i8 represents 64 bit inside NumPy package. Similarly i4 represnts 32 bit.But i16 doesnt exits.

In [21]:
arr2=np.array([(1,2),(4,5)], dtype=[("a",'<i2'),("b",'<i4')])

In [20]:
type(arr2[0][1])

numpy.int32

In [22]:
arr=np.array([[1,3],[3,4]])

In [23]:
arr

array([[1, 3],
       [3, 4]])

In [24]:
arr[0]

array([1, 3])

In [25]:
arr[0][1]

3

In [27]:
type(arr[1][0])

numpy.int32

In [29]:
np.mat(arr)

#here reprentation is same for both arr & matrix

matrix([[1, 3],
        [3, 4]])

In [30]:
np.matrix(arr)

matrix([[1, 3],
        [3, 4]])

In [36]:
l=[1,2,3,4,5,6,7]

In [37]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6, 7])

In [42]:
# if data set is available in form of any array then it will not convert
# here mat i.e matrix is a subset of array so no conversion will be done
# but list is not a array, so it will convert it into array

np.asanyarray(arr)

array([[1, 3],
       [3, 4]])

In [45]:
issubclass(np.matrix,np.ndarray)

#whether matrix is subclass of ndarray..True

True

In [47]:
issubclass(np.ndarray, np.matrix)

#whether ndarray is subclass of matrix..False

False

In [51]:
a=arr
a

#also known as  SHALLOW COPY

array([[1, 3],
       [3, 4]])

In [52]:
b=np.copy(arr)

#copy and defining b
# also known as DEEP COPY

In [53]:
arr[0][0]=67
arr

array([[67,  3],
       [ 3,  4]])

In [54]:
b

array([[1, 3],
       [3, 4]])

Array elements are mutable.

changes made to original array are reflected to "a" only not to its copy "b".

In [55]:
arr[0:10]

array([[67,  3],
       [ 3,  4]])

In [56]:
arr[-1]

array([3, 4])

In [57]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [58]:
np.fromfunction(lambda i, j:i==j,(4,4))

# 4x4 is size of matrix

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [59]:
type(np.fromfunction(lambda i, j:i==j,(4,4)))

numpy.ndarray

In [62]:
np.fromfunction(lambda i, j:i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [63]:
np.fromfunction(lambda i, j:i/j,(4,4))

#here we are getting inf i.e infinity , which exits in NumPy
#we will not get any error

<ipython-input-63-98fded8d1d19>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j:i/j,(4,4))
<ipython-input-63-98fded8d1d19>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j:i/j,(4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

In [67]:
gen=(i*i for i in range(5))

In [65]:
def test (x):
    yield x

In [66]:
test(5)

<generator object test at 0x000001D5E81BC270>

In [68]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [69]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [70]:
gen
for i in gen:
    print(i)

In [74]:
np.fromstring("12,33,5,54", sep=',', dtype=int)

array([12, 33,  5, 54])

In [75]:
np.fromstring('12,33,5,54', sep=',', dtype=int)

array([12, 33,  5, 54])

In [76]:
np.fromstring("12,33,5,54", sep=',', dtype=complex)

array([12.+0.j, 33.+0.j,  5.+0.j, 54.+0.j])

In [77]:
l=[3,4,5,6,7,8]

In [79]:
arr1=np.array(l)

In [83]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])

In [84]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [85]:
type(arr)

numpy.ndarray

In [88]:
arr1.ndim

#how many dimesnion we will be able to visualise

2

In [89]:
arr1.size

#size is no of elements

12

In [90]:
arr1.shape

#rows x columns

(3, 4)

In [91]:
arr1.dtype

dtype('int32')

In [94]:
arr.size

6

In [95]:
arr.ndim

1

In [96]:
arr.shape

(6,)

In [100]:
arr2=np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [101]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [102]:
arr2.size

16

In [105]:
arr2.shape

# it is read out as we have 2 nos (sets) of 2x4 dimensional data

(2, 2, 4)

In [106]:
arr2.ndim

3

In [107]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [108]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [109]:
arr4.ndim

4

In [112]:
arr4.shape

# we have one (1) and four (4) nos of 2x4 data or we have 4 matirx of 2x4 in direction of 1 

(1, 4, 2, 4)

In [115]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [118]:
list(range(6.6,9,.3))

# In list floating values are not possible

TypeError: 'float' object cannot be interpreted as an integer

In [122]:
np.arange(9,6.6,-.3)

#this is possible with arange fucntion and 
#it appears it is accepting upper bound as well which is not actually true 
# since it is decimal value and it tends to infinity
# hence in floting vlaues upper bound is taken, whereas in integer it is excluded

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [123]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [131]:
np.linspace(2,4)
#by default it will generate 50 data sets

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [124]:
np.linspace(1,2,5)

#in between a line is generating a data

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [125]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [129]:
np.linspace(.1,.11,5)

# between .1 to .11 we are genrating 5 dat sets

array([0.1   , 0.1025, 0.105 , 0.1075, 0.11  ])

In [130]:
# zeroes of shape and size are given
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [132]:
np.zeros((2,5,4))

# 2, 5x4 matrix

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [133]:
np.ones(3)

array([1., 1., 1.])

In [134]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [135]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [136]:
np.empty((3,4))

array([[0.        , 0.        , 0.        , 1.        ],
       [0.5       , 0.33333333, 2.        , 1.        ],
       [0.66666667, 3.        , 1.5       , 1.        ]])

In [141]:
np.eye(3)
#by default floating values

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
np.eye(3, dtype=int)

#identity matrices

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [142]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [144]:
np.linspace([1,6],4,endpoint=False)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [147]:
np.linspace(2,4,4,endpoint=False,axis=1)

#axis=1 means 2D data but we had define only 1D dataset 

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [151]:
np.linspace([1,3],4,endpoint=False,axis=1)

#endpoint false means last point is excluded

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [3.  , 3.02, 3.04, 3.06, 3.08, 3.1 , 3.12, 3.14, 3.16, 3.18, 3.2 ,
        3.22, 3.24, 3.26, 3.28, 3.3 , 3.32, 3.34, 3.36, 3.38, 3.4 , 3.42,
        3.44, 3.46, 3.48, 3.5 , 3.52, 3.54, 3.56, 3.58, 3.6 , 3.62, 3.64,
        3.66, 3.68, 3.7 , 3.72, 3.74, 3.76, 3.78, 3.8 , 3.82, 3.84, 3.86,
        3.88, 3.9 , 3.92, 3.94, 3.96, 3.98]])

In [153]:
np.logspace([2,3],4)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [152]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [154]:
np.logspace([2],[3] , axis = 0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [155]:
np.logspace([2],[3] , axis = 1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

#### Widely  used functions in NumPy

In [158]:
d=np.linspace(4,7,40)
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [159]:
d.ndim

1

In [162]:
d.shape

(40,)

In [163]:
d.reshape(40)

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [164]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [165]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [166]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [169]:
np.logspace(2,4,10)

#logarithmic on base 10, from 2 to 4

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [170]:
np.random.rand(3)

array([0.18386707, 0.45650392, 0.53035847])

In [171]:
np.random.randn(5)

array([ 0.21850194, -2.16394908,  0.95345224, -0.44219519,  0.73703898])

In [172]:
np.random.randn(2,2,3)

array([[[ 0.20960212,  0.49187218,  0.46339424],
        [-0.39055489,  1.44553563, -1.55740802]],

       [[ 0.09330738, -0.81464563, -1.75668119],
        [-1.09442417,  0.59183055, -0.21685082]]])

In [174]:
np.random.randn(5,4)

array([[ 1.36350636, -0.9042645 ,  0.1817925 , -0.14049255],
       [ 0.58544707,  0.68340541,  0.7497623 , -0.46381927],
       [ 0.60076162,  1.18783187,  0.30091536,  1.13197877],
       [-1.11940118,  1.69428998,  1.66041793, -0.03763203],
       [-0.70845018, -1.03173488,  0.73131277, -1.68638818]])

In [177]:
np.random.randint(5,15)

9

In [180]:
np.random.randint(5,60, (4,4))

array([[15, 54, 17, 47],
       [ 5, 26, 53, 23],
       [58,  6, 10, 12],
       [22, 22, 54, 46]])

In [181]:
arr=arr = np.random.randint(3,9, ( 3,3))

In [182]:
arr

array([[4, 5, 5],
       [5, 3, 6],
       [7, 7, 4]])

In [183]:
arr.reshape(1,9)

array([[4, 5, 5, 5, 3, 6, 7, 7, 4]])

In [185]:
arr.reshape(9,1)

array([[4],
       [5],
       [5],
       [5],
       [3],
       [6],
       [7],
       [7],
       [4]])

In [186]:
arr.reshape(1,1,9)

array([[[4, 5, 5, 5, 3, 6, 7, 7, 4]]])

In [187]:
arr.reshape(3,3,1)

array([[[4],
        [5],
        [5]],

       [[5],
        [3],
        [6]],

       [[7],
        [7],
        [4]]])

In [188]:
arr.reshape(3,-1)

array([[4, 5, 5],
       [5, 3, 6],
       [7, 7, 4]])

In [189]:
arr.reshape(4,-1)

ValueError: cannot reshape array of size 9 into shape (4,newaxis)

In [190]:
arr.reshape(3,-567)

array([[4, 5, 5],
       [5, 3, 6],
       [7, 7, 4]])

In [191]:
arr.reshape(1,-8765)

array([[4, 5, 5, 5, 3, 6, 7, 7, 4]])

In [192]:
arr.max()

7

In [193]:
arr.min()

3

In [194]:
arr = np.random.randint(4,100, (5,5))

In [195]:
arr

array([[88, 64, 28, 50, 46],
       [94, 56, 35, 83, 41],
       [33, 32,  8, 54, 37],
       [73, 95,  4, 15, 77],
       [40,  4, 39, 50, 16]])

In [196]:
# extracting patricular row , column
arr[3: , 3:]

array([[15, 77],
       [50, 16]])

In [197]:
arr[:,[1,3]]

array([[64, 50],
       [56, 83],
       [32, 54],
       [95, 15],
       [ 4, 50]])

In [198]:
arr

array([[88, 64, 28, 50, 46],
       [94, 56, 35, 83, 41],
       [33, 32,  8, 54, 37],
       [73, 95,  4, 15, 77],
       [40,  4, 39, 50, 16]])

In [201]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [ True, False,  True,  True,  True]])

In [202]:
arr[arr>10]

#data gretaer than 10

array([88, 64, 28, 50, 46, 94, 56, 35, 83, 41, 33, 32, 54, 37, 73, 95, 15,
       77, 40, 39, 50, 16])

In [204]:
arr[arr<10]

array([8, 4, 4])

In [205]:
arr*arr

array([[7744, 4096,  784, 2500, 2116],
       [8836, 3136, 1225, 6889, 1681],
       [1089, 1024,   64, 2916, 1369],
       [5329, 9025,   16,  225, 5929],
       [1600,   16, 1521, 2500,  256]])

In [210]:
arr1=np.random.randint(2,4,(3,3))
arr1

array([[3, 3, 2],
       [2, 2, 3],
       [2, 3, 2]])

In [211]:
arr2=np.random.randint(2,4,(3,3))
arr2

array([[2, 2, 3],
       [3, 3, 2],
       [2, 2, 3]])

In [213]:
arr1*arr2

#it is simple element multiplication, not matrix multiplication
# index multiplication

array([[6, 6, 6],
       [6, 6, 6],
       [4, 6, 6]])

In [214]:
arr1=np.random.randint(2,4,(3,3))

In [215]:
arr2=np.random.randint(2,4,(3,2))

In [216]:
arr1*arr2

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [217]:
arr1@arr2
    
#matrix multiplication

array([[18, 16],
       [16, 14],
       [21, 18]])

In [218]:
arr/0

<ipython-input-218-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [219]:
arr**2

#ssquare of each element

array([[7744, 4096,  784, 2500, 2116],
       [8836, 3136, 1225, 6889, 1681],
       [1089, 1024,   64, 2916, 1369],
       [5329, 9025,   16,  225, 5929],
       [1600,   16, 1521, 2500,  256]], dtype=int32)

BROADCASTING

In [222]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [225]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [226]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

This is boradcasting operation in which each element of array a is casted into matrix np.

In [227]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [228]:
a

array([1, 2, 3, 4])

In [232]:
b=np.array([5,6,7])
b

array([5, 6, 7])

In [233]:
b.reshape(3,1)+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [234]:
b.T

array([5, 6, 7])

In [237]:
b=np.array([[5,6,7]])
b

array([[5, 6, 7]])

In [238]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [239]:
arr=np.random.rand(5,4)

In [240]:
np.sqrt(arr)

array([[0.77637435, 0.4388281 , 0.7142753 , 0.91038646],
       [0.19591132, 0.97720719, 0.5156224 , 0.56982361],
       [0.59669888, 0.72740604, 0.73264083, 0.69967938],
       [0.25887618, 0.7870855 , 0.53258405, 0.82941994],
       [0.69726492, 0.77620793, 0.56188491, 0.94024643]])

In [241]:
np.exp(arr)

array([[1.82714956, 1.21236148, 1.6656063 , 2.29057646],
       [1.03912732, 2.59849878, 1.30456083, 1.38361403],
       [1.4276783 , 1.69743714, 1.71046042, 1.63158386],
       [1.06931352, 1.85800546, 1.32796245, 1.98960761],
       [1.62609002, 1.82667751, 1.37123892, 2.42071595]])

In [242]:
np.log(arr)

array([[-0.50624093, -1.64729505, -0.67297364, -0.18777217],
       [-3.26018631, -0.04611317, -1.32476113, -1.12485686],
       [-1.03268535, -0.63654088, -0.6221994 , -0.71426615],
       [-2.70281081, -0.4788368 , -1.26002909, -0.37405738],
       [-0.72117971, -0.50666969, -1.15291647, -0.12322656]])

In [243]:
np.random.randint(2,5,(5,5))

array([[4, 2, 3, 4, 4],
       [3, 3, 3, 4, 2],
       [4, 3, 4, 4, 3],
       [3, 3, 3, 3, 2],
       [2, 3, 2, 3, 2]])

In [244]:
np.log10(arr1)

array([[0.30103   , 0.47712125, 0.30103   ],
       [0.30103   , 0.30103   , 0.30103   ],
       [0.30103   , 0.47712125, 0.47712125]])

In [248]:
np.random.seed(13)

In [249]:
np.random.rand(2,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

In [250]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])

## THANK YOU & KEEP LEARNING